[package]
name = "vulkanus_3d"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.32.3"
vulkano-win = "0.32.0"
winit = "0.27"
bytemuck = "1.13.1"
vulkano-shaders = "0.32.0"
nalgebra-glm = { version = "0.17.0", features = ["convert-bytemuck"] }
obj-rs = "0.6"